#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

help () {
  cat <<-'EOF'
build
Scripts which packages AWS CLI v2 into an AppImage binary.

Usage:
  ./build <version> [<arch>]
  ./build [-h|--help]

  <version>     Version of AWS CLI
  <arch>        Architecture to build, default to your arch
  -h, --help    Display this message

Example:
  ./build 2.0.0 x86_64
  ./build 2.1.14 aarch64
  ./build 2.1.16
  ./build -h
  ./build --help
EOF
}

if (( $# == 0 )); then
  help
  exit 1
fi

if [[ "${1}" == '-h' || "${1}" == '--help' ]]; then
  help
  exit
fi

VERSION="${1}"
ARCH="${2:-$(uname -m)}"

echo "AWS CLI v2, in a single file - ${VERSION} ${ARCH}"

if [[ "$ARCH" != 'x86_64' && "$ARCH" != 'aarch64' ]]; then
  echo 'Unsupported architecture specified! Arch should be x86_64 or aarch64.'
  exit 1
fi

# Reference: https://docs.appimage.org/packaging-guide/manual.html
cp -R AppDir aws.AppDir

# Download AppImageKit
mkdir tmp
curl -L "https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-$(uname -m).AppImage" -o tmp/appimagetool
curl -L "https://github.com/AppImage/AppImageKit/releases/download/13/AppRun-${ARCH}" -o aws.AppDir/AppRun
curl -L "https://github.com/AppImage/AppImageKit/releases/download/13/runtime-${ARCH}" -o tmp/runtime
chmod +x tmp/appimagetool aws.AppDir/AppRun

# Download and extract AWSCliv2
mkdir -p aws.AppDir/usr/lib
curl "https://awscli.amazonaws.com/awscli-exe-linux-${ARCH}-${VERSION}.zip" -o tmp/aws.zip
(cd tmp; unzip -q aws.zip 'aws/dist/*')
mv tmp/aws/dist aws.AppDir/usr/lib/aws

# Package
tmp/appimagetool -n aws.AppDir --runtime-file tmp/runtime
